INSERT INTO APPLICATION_USER 
	(ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, ADDRESS, CITY, COUNTRY, CREDENTIALS_NON_EXPIRED, EMAIL, ENABLED, LANGUAGE, NAME, PASSWORD, PASSWORD_RECOVERY_HASH, USERNAME, VERSION) 
VALUES 
	(true, true, '1', '1', '1', true, 'pablo@gmail.com', true, '1', 'pablo', '{bcrypt}$2a$10$08d0l3aRNN.DQ/CgHFmZNOUmpaWSjWsTRzN/Dcd.1WEhpQ13CEDxK', 'secret', 'pablo', 1);

INSERT INTO application_user_role (ROLE, USER_ID) VALUES ('USER', '1');