version: '3.1'

services:
  db:
    image: postgres:14
    volumes: 
     - pgdata:/var/lib/postgresql/data
    ports: 
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: app
#  solr:
#    image: solr:8.11
#    ports:
#     - "9983:9983"
#     - "8983:8983"
#    volumes:
#      - ./solr-data:/opt/solr/server/solr/mycores
#    entrypoint:
#      - docker-entrypoint.sh
#      - solr
#      - start
#      - -c
#      - -f
volumes:
  pgdata:
